### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by hkonnet** [BestBuyAPIs/bestbuy-sdk-php#3]
Just want to ask that how items/products will be paginate? 

`bby->products('name=iphone*')`

This returns only  items from 0-10.. what if i want to see more?

**Comment by troymccabe** [comment]
You can use the `$responseConfig` parameter of each of the methods work with with paging. The keys in that array are the values found in the documentation @ https://bestbuyapis.github.io/api-documentation/#pagination.

Here's an example:

`$bby->products('name=iphone*', ['pageSize' => 100, 'page' => 2]);` would give you the second of many pages, with 100 products.

Hope this helps

**Comment by hkonnet** [comment]
@troymccabe Thank you.. that helps..
